name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Encore
        uses: encoredev/setup-action@v1
        with:
          version: latest
      
      - name: Run Encore tests
        run: encore test ./...
      
      - name: Run Encore linter
        run: encore lint
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Encore
        uses: encoredev/setup-action@v1
        with:
          version: latest
      
      - name: Deploy to Encore Cloud
        run: encore deploy production
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }} 